### ISSUE TITLE
Stop server at the end of a test

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel#12]
Currently the drop and the storage server are started automatically but not shut down automatically. There is gradle task for that but it doesn't seem to work (at least on my machine).

**Comment by L-Henke** [comment]
It works for me, no python or nodejs process visible after the execution.

**Comment by hartmannaf** [comment]
I will look into it, but there should be no problems, besides that the processes are in the background. 
At the moment it looks like the kill task will be executed before the tests on systems, where the server processes stay after gradle finished executing.

**Comment by jasinai** [comment]
My servers are killed at the beginning of the build.

**Comment by thechauffeur** [comment]
It would be nice if they will be killed after -- not prior to -- executing the tests.
