### ISSUE TITLE
Use git's --depth option to speed-up travis

### ISSUE THREAD

**Issue by cburkert** [Qabel/qabel#16]
We should use the depth option in both `git clone` and `git submodule update` to speed up travis CI. This avoids downloading the whole history, which is totally unneeded for testing.

`git clone --depth 1 https://github.com/Qabel/qabel.git`

and

`git submodule update --depth 1`

**Comment by cburkert** [comment]
@NanNor you can change this since you are already touching travis config.

**Comment by thechauffeur** [comment]
Good idea :+1:

**Comment by NanNor** [comment]
change this only in qabel-core? I use the depth option for the .travis.yml in qabel-storage and qabel-drop now.

**Comment by jasinai** [comment]
Not only in qabel-core. It's good to use the option in qabel-storage and qabel-drop, too. :+1:

**Comment by cburkert** [comment]
Exactly, what @jasinai said. This option is useful for every travis config using `git` commands.
