### ISSUE TITLE
Horribly broken on Windows

### ISSUE THREAD

**Issue by jan-schreib** [Qabel/qabel#28]
- build.gradle is wrong and doesn't care on wich OS it is used
- commands to start the servers are wrong
- since python3.x virtualenv is included in python

This has to be fixed until the beta.

**Comment by audax** [comment]
Or we just remove the meta repo and us the desktop repo for desktop development.

**Comment by jan-schreib** [comment]
Fine with me.

**Comment by jan-schreib** [comment]
closed via 409db01a9c4a5fe3dca4708d069ff8cba2c88ce1
discussed with @audax
