### ISSUE TITLE
Add qabel-drop and qabel-storage to this META repository

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel#7]
* Update web hooks
* We could also use these repos wisely like doing a ```./gradlew check``` in the ```qabel``` repo for automatically starting the servers etc.

**Comment by Gottox** [comment]
* [x] Update Webhooks
* [ ] Gradle check support

**Comment by k-c13** [comment]
See #264

**Comment by thechauffeur** [comment]
@jan-schreib look for someone else or support @hartmannaf.

**Comment by jan-schreib** [comment]
@hartmannaf I asked you to do this a while ago, any progress?

**Comment by thechauffeur** [comment]
Solved by #9
